<?php

/**
 * @file
 * Allows node-related Views to be filtered by path aliases.
 */

/**
 * Implements hook_menu().
 */
function views_url_alias_node_menu() {
  $items['admin/structure/views/settings/alias/node'] = array(
    'title' => 'Rebuild alias node table',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('views_url_alias_node_admin'),
    'access arguments' => array('administer views'),
    'file' => 'views_url_alias_node.admin.inc',
    'file path' => drupal_get_path('module', 'views_url_alias_node'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_node_insert().
 */
function views_url_alias_node_insert($node) {
  _views_url_alias_update_node($node);
}

/**
 * Implements hook_node_update().
 */
function views_url_alias_node_update($node) {
  _views_url_alias_update_node($node);
}

/**
 * Implements hook_node_delete().
 */
function views_url_alias_node_delete($node) {
  _views_url_alias_update_node($node, TRUE);
}

/**
 * Update node's alias entries.
 */
function _views_url_alias_update_node($node, $delete = FALSE) {
  db_query('DELETE FROM {views_url_alias_node} WHERE nid=%d', $node->nid);

  if (!empty($node->path) && !$delete) {
    db_query("INSERT INTO {views_url_alias_node} (dst, nid) VALUE ('%s', %d)", $node->path, $node->nid);
  }
}

/**
 * Implementation of hook_views_api().
 */
function views_url_alias_node_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'views_url_alias_node'),
  );
}

/**
 * Rebuild view_url_alias_node table.
 *
 * This function typically only need to called when this module is installed.
 */
function _views_url_alias_node_rebuild() {
  // Purge view_url_alias_node table.
  db_truncate('views_url_alias_node')->execute();

  // Populate view_url_alias_node table.
  // @TODO Convert to D7 DBTNG somehow?
  db_query("INSERT INTO {views_url_alias_node} (nid, alias)
    SELECT n.nid, ua.alias FROM {url_alias} ua INNER JOIN node AS n ON CONCAT('node/', n.nid) = ua.source");

  // Display message
  drupal_set_message( t('The %table table has been successfully rebuilt.', array('%table' => 'views_url_alias_node')) );
}
